services:
  
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  
  api-service:
    build:
      context: .
      dockerfile: ./base/Dockerfile
      args:
        SERVICE_NAME: "api-service"
    ports:
     - "8080:8080"
    volumes:
      - ./api-service:/app/api-service
      - /app/api-service/node_modules

  backend-service:
    build:
      context: .
      dockerfile: ./base/Dockerfile
      args:
        SERVICE_NAME: "backend-service"
    ports:
      - "8081:8081"
    volumes:
      - ./backend-service:/app/backend-service
      - /app/backend-service/node_modules
  
  mysql:
    container_name: 'mysql-container'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=messageappdatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'